In [67]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sb

In [94]:
df = pd.read_csv('data/Car_Purchasing_Data.csv')

In [20]:
df.head(2)

Customer Name                                    Customer e-mail   Country  \
0  Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu  Bulgaria   
1  Harlan Barnes                                eu.dolor@diam.co.uk    Belize   

   Gender        Age  Annual Salary  Credit Card Debt    Net Worth  \
0       0  41.851720    62812.09301      11609.380910  238961.2505   
1       0  40.870623    66646.89292       9572.957136  530973.9078   

   Car Purchase Amount  
0          35321.45877  
1          45115.52566

In [ ]:
# 구매 금액 예측하는 인공지능 개발 

In [19]:
df.isna().sum()

Customer Name          0
Customer e-mail        0
Country                0
Gender                 0
Age                    0
Annual Salary          0
Credit Card Debt       0
Net Worth              0
Car Purchase Amount    0
dtype: int64

In [22]:
df['Country'].nunique()

211

In [45]:
../data

ls: ../data/Car_Purchasing_Data.csv: No such file or directory


In [26]:
df['Country'].value_counts()

Country
Israel                 6
Mauritania             6
Bolivia                6
Greenland              5
Saint Barth?emy        5
                      ..
El Salvador            1
Denmark                1
Oman                   1
Trinidad and Tobago    1
marlal                 1
Name: count, Length: 211, dtype: int64

In [27]:
df.head(2)

Customer Name                                    Customer e-mail   Country  \
0  Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu  Bulgaria   
1  Harlan Barnes                                eu.dolor@diam.co.uk    Belize   

   Gender        Age  Annual Salary  Credit Card Debt    Net Worth  \
0       0  41.851720    62812.09301      11609.380910  238961.2505   
1       0  40.870623    66646.89292       9572.957136  530973.9078   

   Car Purchase Amount  
0          35321.45877  
1          45115.52566

In [30]:
y = df['Car Purchase Amount']

In [31]:
X = df.loc[ : , 'Age' :'Net Worth']

In [32]:
X

Age  Annual Salary  Credit Card Debt    Net Worth
0    41.851720    62812.09301      11609.380910  238961.2505
1    40.870623    66646.89292       9572.957136  530973.9078
2    43.152897    53798.55112      11160.355060  638467.1773
3    58.271369    79370.03798      14426.164850  548599.0524
4    57.313749    59729.15130       5358.712177  560304.0671
..         ...            ...               ...          ...
495  41.462515    71942.40291       6995.902524  541670.1016
496  37.642000    56039.49793      12301.456790  360419.0988
497  53.943497    68888.77805      10611.606860  764531.3203
498  59.160509    49811.99062      14013.034510  337826.6382
499  46.731152    61370.67766       9391.341628  462946.4924

[500 rows x 4 columns]

In [33]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...     
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64

In [37]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [76]:
from sklearn.linear_model import  LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [57]:
regressor1 = LinearRegression()

In [60]:
regressor1.fit(X_train, y_train)

LinearRegression()

In [70]:
y_pred = regressor1.predict(X_test)

In [71]:
y_pred

array([51552.27823461, 53849.0012841 , 10091.73108141, 44437.16635402,
       42774.33239837, 62029.10132835, 22628.545919  , 49093.39083694,
       47988.62186378, 56510.76156526, 41027.67930587, 31300.08924025,
       46848.07564512, 50664.77851822, 31410.35151344, 30721.00772391,
       50540.61503653, 36018.4793374 , 57306.61926108, 47869.48825814,
       38171.08722902, 64391.62412183, 41351.91953226, 38400.14559457,
       45060.57699687, 39765.59526664, 44524.15268274, 44430.94341352,
       57302.12586833, 52709.07901197, 35659.95363152, 50296.41457285,
       22682.0361177 , 55545.13314546, 49721.83824384, 37076.98606623,
       39270.08101508, 52056.81002717, 35778.08753317, 41319.94609942,
       31087.49383622, 33637.58953367, 42210.51724045, 64545.08400894,
       66163.41479692, 53658.12458011, 47695.36485318, 46324.48055077,
       49991.47540485, 41426.0353031 , 56229.87726635, 59538.63137253,
       46380.07914103, 41458.9818475 , 58839.68016352, 33130.36287534,
      

In [64]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [72]:
mean_squared_error(y_test, y_pred)

2.4547174765278577

In [73]:
r2_score(y_test, y_pred)

0.9999999783631199

NameError: name 'df_y' is not defined

In [77]:
regressor2 = RandomForestRegressor()

In [78]:
regressor2.fit(X_train, y_train)

RandomForestRegressor()

In [79]:
y_pred2 = regressor2.predict(X_test)

In [80]:
y_pred2

array([53160.2958527, 53631.1138731, 20965.3354265, 44545.1325587,
       43778.719007 , 59220.9011172, 25131.6312425, 49166.4075657,
       46949.2048988, 53808.0118856, 40841.1676078, 32136.741065 ,
       46064.5944726, 50580.5683192, 30502.101916 , 31895.3076431,
       47772.2456356, 35722.370954 , 54086.6872891, 47922.5635576,
       40688.8644586, 62806.0526763, 41490.0096612, 37957.0666073,
       45219.0317579, 40246.3884568, 45983.4752136, 44260.6870612,
       54400.0923928, 52517.5117006, 36160.5829573, 52293.8671817,
       22366.8741707, 49717.36665  , 50401.9011707, 34859.4091732,
       37961.9242647, 50346.8408178, 40191.4138535, 41473.4078151,
       34090.603699 , 36472.992197 , 43552.1821187, 63894.3220294,
       65067.8977789, 54034.4208074, 47258.7309692, 46253.5394502,
       49252.5862197, 41752.1836856, 43235.3551029, 59496.5475161,
       46721.1232245, 40046.8015867, 57296.4156525, 32772.1272595,
       32702.5361419, 50386.2607334, 52355.1202542, 38816.8279

In [81]:
mean_squared_error(y_test, y_pred2)

6976875.846259722

In [82]:
r2_score(y_test, y_pred2)

0.9385029733614374

In [83]:
# 신규 고객에게 얼마나 팔 수 있을지 예측
# 40세, 50000불 연봉, 600000불 순자산, 10000불 신용카드 빚

In [84]:
new_data = np.array([40, 50000, 10000, 600000 ])

In [86]:
# -1 의 경우 컬럼수만큼 지정해서 만들어준다. 
new_data = new_data.reshape(1, -1)

In [88]:
regressor1.predict(new_data)

/opt/anaconda3/envs/hi/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([37021.92477431])

In [89]:
import joblib

In [95]:
joblib.dump(regressor1, 'model/regressor1.pkl')

['model/regressor1.pkl']